CREATE DATABASE IF NOT EXISTS `bcit_parkly`;

USE `bcit_parkly`;

DROP TABLE IF EXISTS `reservations`;

DROP TABLE IF EXISTS `parking_stall_vertices`;

DROP TABLE IF EXISTS `parking_stalls`;

DROP TABLE IF EXISTS `parking_lot_valid_permits`;

DROP TABLE IF EXISTS `parking_lot_schedules`;

DROP TABLE IF EXISTS `parking_lot_address`;

DROP TABLE IF EXISTS `parking_lots`;

DROP TABLE IF EXISTS `customers`;

DROP TABLE IF EXISTS `sessions`;

CREATE TABLE `customers` (
    customer_id INT PRIMARY KEY AUTO_INCREMENT,
    customer_name VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL UNIQUE,
    phone VARCHAR(10),
    valid_permits VARCHAR(20) NOT NULL
);

CREATE TABLE `parking_lots` (
    lot_id INT PRIMARY KEY AUTO_INCREMENT,
    lot_floor VARCHAR(10) NOT NULL UNIQUE,
    lot_capacity INT NOT NULL,
    lat DECIMAL(30, 20),
    lon DECIMAL(30, 20),
    lot_description TEXT,
    lot_name VARCHAR(50) NOT NULL
);

CREATE TABLE `parking_lot_address`(
    address_id INT PRIMARY KEY AUTO_INCREMENT,
    street VARCHAR(100) NOT NULL,
    city VARCHAR(50) NOT NULL,
    province VARCHAR(50) NOT NULL,
    postal_code VARCHAR(10) NOT NULL,
    lot_id INT NOT NULL,
    FOREIGN KEY (lot_id) REFERENCES parking_lots (lot_id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE `parking_lot_schedules` (
    schedule_id INT PRIMARY KEY AUTO_INCREMENT,
    daytimePrice DECIMAL(10, 2),
    daytimeRate DECIMAL(10, 2),
    daytime_start_time TIME,
    daytime_end_time TIME,
    daytimeMaxPrice DECIMAL(10, 2),
    eveningPrice DECIMAL(10, 2),
    eveningRate DECIMAL(10, 2),
    evening_start_time TIME,
    evening_end_time TIME,
    eveningMaxPrice DECIMAL(10, 2),
    weekendPrice DECIMAL(10, 2),
    weekendRate DECIMAL(10, 2),
    weekend_start_time TIME,
    weekend_end_time TIME,
    weekendMaxPrice DECIMAL(10, 2),
    rate_unit VARCHAR(20) NOT NULL CHECK (rate_unit IN ('30 min', 'hr')),
    lot_id INT NOT NULL,
    FOREIGN KEY (lot_id) REFERENCES parking_lots (lot_id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE `parking_lot_valid_permits` (
    lot_id INT NOT NULL,
    valid_permits VARCHAR(20) NOT NULL CHECK (valid_permits IN ('staff', 'student')),
    PRIMARY KEY (lot_id, valid_permits),
    FOREIGN KEY (lot_id) REFERENCES parking_lots (lot_id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE `parking_stalls` (
    stall_id INT PRIMARY KEY AUTO_INCREMENT,
    occupied BOOLEAN DEFAULT FALSE,
    parking_type TEXT NOT NULL CHECK (
        parking_type IN ('regular', 'electric', 'small', 'handicap')
    ),
    -- centroid_lat DECIMAL(10, 7),
    -- centroid_lng DECIMAL(10, 7),
    -- polygon_wkt TEXT,
    -- coordinates_json JSON,
    -- POLYGON GEOMETRY SRID 4326 NULL,
    lot_id INT,
    FOREIGN KEY (lot_id) REFERENCES parking_lots (lot_id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- CREATE TABLE `parking_stall_vertices` (
--     vertex_order INT NOT NULL,
--     lat DECIMAL(10, 7) NOT NULL,
--     lng DECIMAL(10, 7) NOT NULL,
--     stall_id INT NOT NULL,
--     PRIMARY KEY (stall_id, vertex_order),
--     FOREIGN KEY (stall_id) REFERENCES parking_stalls (stall_id) ON DELETE CASCADE ON UPDATE CASCADE
-- );
CREATE TABLE `reservations` (
    reservation_id INT PRIMARY KEY AUTO_INCREMENT,
    purchase_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    license_plate VARCHAR(10) NOT NULL UNIQUE,
    total_cost DECIMAL(10, 2) NOT NULL,
    stall_location VARCHAR(20) NOT NULL,
    lot_id INT,
    stall_id INT,
    customer_id INT,
    FOREIGN KEY (customer_id) REFERENCES customers (customer_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (lot_id) REFERENCES parking_lots (lot_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (stall_id) REFERENCES parking_stalls (stall_id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE `sessions` (
    id VARCHAR(200) NOT NULL PRIMARY KEY,
    secret_hash MEDIUMBLOB NOT NULL,
    created_at DATETIME NOT NULL
);

INSERT INTO parking_lots(lot_floor, lot_capacity, lat, lon, lot_description, lot_name) VALUES
    ('1', 58, 49.28350846808849, -123.11494653742396, 'BCIT Downtown Campus Lot', 'BCIT Campus Parking'),
    ('2', 28, 49.282255197149816, -123.11535548504304, 'Lot 1037', '619 Richards Street Lot'),
    ('3', 67, 49.28541860364103, -123.11753337849295, 'Lot 4116', 'Diamond Parking'),
    ('B1', 74, 49.28525142611815, -123.11953798092193, 'Precise ParkLink', 'Park Place Parking'),
    ('B2', 57, 49.28045903416459, -123.11897398685132, 'Lot 055 - H&Y Mart', 'Parking Indigo Vancouver');

INSERT INTO customers (customer_name, email, phone, valid_permits) VALUES
    ('Jordan Patel', 'jordan.patel@example.com', '6045550107', 'student'),
    ('Priya Nair', 'priya.nair@example.com', '6045550108', 'staff'),
    ('Liam Ortiz', 'liam.ortiz@example.com', '6045550109', 'student'),
    ('Grace Kim', 'grace.kim@example.com', '6045550110', 'staff'),
    ('Maria Garcia', 'maria.garcia@example.com', '6045550111', 'student'),
    ('David Chen', 'david.chen@example.com', '6045550112', 'staff'),
    ('Sarah Johnson', 'sarah.johnson@example.com', '6045550113', 'student'),
    ('Michael Thompson', 'michael.t@example.com', '6045550114', 'staff'),
    ('Emily Rodriguez', 'emily.r@example.com', '6045550115', 'student'),
    ('James Wilson', 'james.wilson@example.com', '6045550116', 'staff'),
    ('Lisa Anderson', 'lisa.anderson@example.com', '6045550117', 'student'),
    ('Christopher Lee', 'christopher.lee@example.com', '6045550118', 'staff');

-- Parking Stalls Configuration
-- Lot 1 (FULL) - 56 stalls
-- Lot 2 (CLOSED) - 30 stalls
-- Lot 3 (AVAILABLE) - 95 stalls
-- Lot 4 (AVAILABLE - LIMITED SPACES) - 75 stalls
-- Lot 5 (AVAILABLE) - 60 stalls
INSERT INTO parking_stalls (occupied, parking_type, lot_id) VALUES
    (TRUE, 'regular', 1),
    (TRUE, 'electric', 1),
    (TRUE, 'small', 1),
    (TRUE, 'handicap', 1),
    (TRUE, 'regular', 1),
    (TRUE, 'electric', 1),
    (TRUE, 'regular', 1),
    (TRUE, 'handicap', 1),
    (TRUE, 'regular', 1),
    (TRUE, 'regular', 1),
    (TRUE, 'regular', 1),
    (TRUE, 'regular', 1),
    (TRUE, 'regular', 1),
    (TRUE, 'electric', 1),
    (TRUE, 'electric', 1),
    (TRUE, 'electric', 1),
    (TRUE, 'electric', 1),
    (TRUE, 'electric', 1),
    (TRUE, 'small', 1),
    (TRUE, 'small', 1),
    (TRUE, 'small', 1),
    (TRUE, 'small', 1),
    (TRUE, 'small', 1),
    (TRUE, 'handicap', 1),
    (TRUE, 'handicap', 1),
    (TRUE, 'handicap', 1),
    (TRUE, 'handicap', 1),
    (TRUE, 'handicap', 1),
    (TRUE, 'regular', 1),
    (TRUE, 'regular', 1),
    (TRUE, 'regular', 1),
    (TRUE, 'regular', 1),
    (TRUE, 'regular', 1),
    (TRUE, 'electric', 1),
    (TRUE, 'electric', 1),
    (TRUE, 'electric', 1),
    (TRUE, 'electric', 1),
    (TRUE, 'electric', 1),
    (TRUE, 'small', 1),
    (TRUE, 'small', 1),
    (TRUE, 'small', 1),
    (TRUE, 'small', 1),
    (TRUE, 'small', 1),
    (TRUE, 'handicap', 1),
    (TRUE, 'handicap', 1),
    (TRUE, 'handicap', 1),
    (TRUE, 'handicap', 1),
    (TRUE, 'handicap', 1),
    (TRUE, 'regular', 1),
    (TRUE, 'regular', 1),
    (TRUE, 'regular', 1),
    (TRUE, 'regular', 1),
    (TRUE, 'regular', 1),
    (TRUE, 'electric', 1),
    (TRUE, 'electric', 1),
    (TRUE, 'electric', 1),
    (TRUE, 'electric', 1),
    (TRUE, 'electric', 1),
    (TRUE, 'regular', 2),
    (FALSE, 'regular', 2),
    (TRUE, 'electric', 2),
    (FALSE, 'electric', 2),
    (TRUE, 'small', 2),
    (FALSE, 'small', 2),
    (TRUE, 'handicap', 2),
    (FALSE, 'handicap', 2),
    (TRUE, 'regular', 2),
    (FALSE, 'regular', 2),
    (TRUE, 'regular', 2),
    (FALSE, 'electric', 2),
    (TRUE, 'electric', 2),
    (FALSE, 'small', 2),
    (TRUE, 'small', 2),
    (FALSE, 'handicap', 2),
    (TRUE, 'handicap', 2),
    (FALSE, 'regular', 2),
    (TRUE, 'regular', 2),
    (FALSE, 'regular', 2),
    (TRUE, 'electric', 2),
    (FALSE, 'electric', 2),
    (TRUE, 'small', 2),
    (FALSE, 'small', 2),
    (TRUE, 'handicap', 2),
    (FALSE, 'handicap', 2),
    (TRUE, 'regular', 2),
    (FALSE, 'regular', 2),
    (FALSE, 'regular', 3),
    (TRUE, 'regular', 3),
    (FALSE, 'electric', 3),
    (TRUE, 'electric', 3),
    (FALSE, 'small', 3),
    (TRUE, 'small', 3),
    (TRUE, 'handicap', 3),
    (FALSE, 'regular', 3),
    (FALSE, 'regular', 3),
    (FALSE, 'regular', 3),
    (FALSE, 'regular', 3),
    (FALSE, 'regular', 3),
    (FALSE, 'regular', 3),
    (FALSE, 'regular', 3),
    (FALSE, 'regular', 3),
    (FALSE, 'regular', 3),
    (FALSE, 'regular', 3),
    (FALSE, 'electric', 3),
    (FALSE, 'electric', 3),
    (FALSE, 'electric', 3),
    (FALSE, 'electric', 3),
    (FALSE, 'electric', 3),
    (FALSE, 'electric', 3),
    (FALSE, 'electric', 3),
    (FALSE, 'electric', 3),
    (FALSE, 'electric', 3),
    (FALSE, 'electric', 3),
    (FALSE, 'small', 3),
    (FALSE, 'small', 3),
    (FALSE, 'small', 3),
    (FALSE, 'small', 3),
    (FALSE, 'small', 3),
    (FALSE, 'small', 3),
    (FALSE, 'small', 3),
    (FALSE, 'small', 3),
    (FALSE, 'small', 3),
    (FALSE, 'small', 3),
    (FALSE, 'handicap', 3),
    (FALSE, 'handicap', 3),
    (FALSE, 'handicap', 3),
    (FALSE, 'handicap', 3),
    (FALSE, 'handicap', 3),
    (TRUE, 'regular', 3),
    (TRUE, 'regular', 3),
    (TRUE, 'regular', 3),
    (TRUE, 'regular', 3),
    (TRUE, 'electric', 3),
    (TRUE, 'electric', 3),
    (TRUE, 'electric', 3),
    (FALSE, 'regular', 3),
    (FALSE, 'regular', 3),
    (FALSE, 'regular', 3),
    (FALSE, 'regular', 3),
    (FALSE, 'regular', 3),
    (FALSE, 'regular', 3),
    (FALSE, 'regular', 3),
    (FALSE, 'regular', 3),
    (FALSE, 'regular', 3),
    (FALSE, 'electric', 3),
    (FALSE, 'electric', 3),
    (FALSE, 'electric', 3),
    (FALSE, 'electric', 3),
    (FALSE, 'electric', 3),
    (FALSE, 'small', 3),
    (FALSE, 'small', 3),
    (FALSE, 'small', 3),
    (FALSE, 'handicap', 3),
    (TRUE, 'regular', 4),
    (TRUE, 'regular', 4),
    (TRUE, 'electric', 4),
    (TRUE, 'electric', 4),
    (TRUE, 'handicap', 4),
    (FALSE, 'handicap', 4),
    (TRUE, 'regular', 4),
    (TRUE, 'regular', 4),
    (TRUE, 'regular', 4),
    (TRUE, 'regular', 4),
    (TRUE, 'regular', 4),
    (TRUE, 'regular', 4),
    (TRUE, 'regular', 4),
    (TRUE, 'regular', 4),
    (TRUE, 'regular', 4),
    (TRUE, 'regular', 4),
    (TRUE, 'electric', 4),
    (TRUE, 'electric', 4),
    (TRUE, 'electric', 4),
    (TRUE, 'electric', 4),
    (TRUE, 'electric', 4),
    (TRUE, 'electric', 4),
    (TRUE, 'electric', 4),
    (TRUE, 'electric', 4),
    (TRUE, 'electric', 4),
    (TRUE, 'electric', 4),
    (TRUE, 'small', 4),
    (TRUE, 'small', 4),
    (TRUE, 'small', 4),
    (TRUE, 'small', 4),
    (TRUE, 'small', 4),
    (TRUE, 'small', 4),
    (TRUE, 'small', 4),
    (TRUE, 'small', 4),
    (TRUE, 'small', 4),
    (TRUE, 'small', 4),
    (TRUE, 'handicap', 4),
    (TRUE, 'handicap', 4),
    (TRUE, 'handicap', 4),
    (TRUE, 'handicap', 4),
    (TRUE, 'handicap', 4),
    (TRUE, 'handicap', 4),
    (TRUE, 'handicap', 4),
    (TRUE, 'handicap', 4),
    (TRUE, 'handicap', 4),
    (TRUE, 'handicap', 4),
    (TRUE, 'regular', 4),
    (TRUE, 'regular', 4),
    (TRUE, 'regular', 4),
    (TRUE, 'regular', 4),
    (TRUE, 'regular', 4),
    (TRUE, 'regular', 4),
    (TRUE, 'regular', 4),
    (TRUE, 'regular', 4),
    (TRUE, 'regular', 4),
    (TRUE, 'regular', 4),
    (TRUE, 'electric', 4),
    (TRUE, 'electric', 4),
    (TRUE, 'electric', 4),
    (TRUE, 'electric', 4),
    (TRUE, 'electric', 4),
    (TRUE, 'electric', 4),
    (TRUE, 'electric', 4),
    (TRUE, 'electric', 4),
    (TRUE, 'electric', 4),
    (FALSE, 'regular', 4),
    (FALSE, 'regular', 4),
    (FALSE, 'regular', 4),
    (FALSE, 'regular', 4),
    (FALSE, 'regular', 4),
    (FALSE, 'electric', 4),
    (FALSE, 'electric', 4),
    (FALSE, 'electric', 4),
    (FALSE, 'small', 4),
    (FALSE, 'regular', 5),
    (FALSE, 'regular', 5),
    (FALSE, 'regular', 5),
    (FALSE, 'regular', 5),
    (FALSE, 'regular', 5),
    (FALSE, 'regular', 5),
    (FALSE, 'regular', 5),
    (FALSE, 'regular', 5),
    (FALSE, 'regular', 5),
    (FALSE, 'regular', 5),
    (FALSE, 'regular', 5),
    (FALSE, 'regular', 5),
    (FALSE, 'regular', 5),
    (FALSE, 'electric', 5),
    (FALSE, 'electric', 5),
    (FALSE, 'electric', 5),
    (FALSE, 'electric', 5),
    (FALSE, 'electric', 5),
    (FALSE, 'electric', 5),
    (FALSE, 'electric', 5),
    (FALSE, 'electric', 5),
    (FALSE, 'electric', 5),
    (FALSE, 'electric', 5),
    (FALSE, 'electric', 5),
    (FALSE, 'electric', 5),
    (FALSE, 'electric', 5),
    (FALSE, 'small', 5),
    (FALSE, 'small', 5),
    (FALSE, 'small', 5),
    (FALSE, 'small', 5),
    (FALSE, 'small', 5),
    (FALSE, 'small', 5),
    (FALSE, 'small', 5),
    (FALSE, 'small', 5),
    (FALSE, 'small', 5),
    (FALSE, 'small', 5),
    (FALSE, 'small', 5),
    (FALSE, 'handicap', 5),
    (FALSE, 'handicap', 5),
    (FALSE, 'handicap', 5),
    (FALSE, 'handicap', 5),
    (FALSE, 'handicap', 5),
    (FALSE, 'handicap', 5),
    (FALSE, 'handicap', 5),
    (FALSE, 'handicap', 5),
    (FALSE, 'handicap', 5),
    (FALSE, 'handicap', 5),
    (TRUE, 'regular', 5),
    (TRUE, 'regular', 5),
    (TRUE, 'electric', 5),
    (TRUE, 'small', 5),
    (TRUE, 'small', 5),
    (TRUE, 'handicap', 5),
    (FALSE, 'regular', 5),
    (FALSE, 'regular', 5),
    (FALSE, 'electric', 5),
    (FALSE, 'small', 5);

INSERT INTO reservations (license_plate, total_cost, stall_location, lot_id, stall_id, customer_id) VALUES
    ('BC5J6K', 5.00, 'L1-01', 1, 1, 1),
    ('BC6L7M', 7.50, 'L1-02', 1, 2, 2),
    ('BC7N8P', 2.50, 'L1-03', 1, 3, 3),
    ('BC8Q9R', 6.50, 'L2-01', 2, 9, 5),
    ('BC9S0T', 8.00, 'L2-02', 2, 10, 6),
    ('BC0U1V', 4.00, 'L2-03', 2, 11, 7),
    ('BC1W2X', 5.50, 'L3-01', 3, 17, 8),
    ('BC2Y3Z', 7.00, 'L3-02', 3, 18, 9),
    ('BC3A4B', 3.50, 'L4-01', 4, 25, 10),
    ('BC4C5D', 6.00, 'L4-02', 4, 26, 11),
    ('BC5E6F', 5.25, 'L1-07', 1, 7, 12);

INSERT INTO `parking_lot_address` (street, city, province, postal_code, lot_id) VALUES
    ('555 Seymour St', 'Vancouver', 'BC', 'V6B 3H6', 1),
    ('619 Richards St', 'Vancouver', 'BC', 'V6B 5E3', 2),
    ('550 Hornby St 2E7', 'Vancouver', 'BC', 'V6C 2E7', 3),
    ('666 Burrard St', 'Vancouver', 'BC', 'V6C 3P6', 4),
    ('550 Robson St', 'Vancouver', 'BC', 'V6B 2B7', 5);

INSERT INTO `parking_lot_schedules` (daytimePrice, daytimeRate, daytime_start_time, daytime_end_time, daytimeMaxPrice, eveningPrice, eveningRate, evening_start_time, evening_end_time, eveningMaxPrice, weekendPrice, weekendRate, weekend_start_time, weekend_end_time, weekendMaxPrice, rate_unit, lot_id) VALUES
    (5.00, 1.00, '08:00:00', '18:00:00', 25.00, 3.00, 1.00, '18:00:00', '00:00:00', 12.00, 2.50, 1.00, '06:00:00', '18:00:00', 10.00, 'hr', 1),
    (5.50, 1.00, '08:00:00', '18:00:00', 27.50, 3.25, 1.00, '18:00:00', '00:00:00', 13.00, 2.75, 1.00, '06:00:00', '18:00:00', 11.00, 'hr', 2),
    (4.75, 1.00, '07:00:00', '19:00:00', 24.00, 2.75, 1.00, '19:00:00', '07:00:00', 11.00, 2.25, 1.00, '06:00:00', '19:00:00', 9.00, 'hr', 3),
    (6.00, 1.00, '08:00:00', '20:00:00', 30.00, 3.50, 1.00, '20:00:00', '08:00:00', 14.00, 3.00, 1.00, '06:00:00', '20:00:00', 12.00, 'hr', 4),
    (5.25, 1.00, '07:00:00', '19:00:00', 26.00, 3.00, 1.00, '19:00:00', '07:00:00', 12.00, 2.50, 1.00, '06:00:00', '19:00:00', 10.00, 'hr', 5);

INSERT INTO `parking_lot_valid_permits` (lot_id, valid_permits) VALUES
    (1, 'staff'),
    (1, 'student'),
    (2, 'staff'),
    (2, 'student'),
    (3, 'staff'),
    (3, 'student'),
    (4, 'staff'),
    (4, 'student'),
    (5, 'staff'),
    (5, 'student');