on:
  push:
    branches:
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
      GOOGLE_MAP_ID: ${{ secrets.GOOGLE_MAP_ID }}
      MODE: ${{ secrets.MODE }}
    steps:
      - uses: actions/checkout@v6
      - name: Set up Node.js v25.9.0
        uses: actions/setup-node@v6
        with:
          node-version: "25"
      - name: Install dependencies
        run: |
          npm install
      - name: Check required secrets
        run: |
          test -n "$MYSQL_HOST" || (echo "MYSQL_HOST is missing" && exit 1)
          test -n "$MYSQL_PORT" || (echo "MYSQL_PORT is missing" && exit 1)
          test -n "$MYSQL_USER" || (echo "MYSQL_USER is missing" && exit 1)
          test -n "$MYSQL_PASSWORD" || (echo "MYSQL_PASSWORD is missing" && exit 1)
          test -n "$MYSQL_DATABASE" || (echo "MYSQL_DATABASE is missing" && exit 1)
          test -n "$GOOGLE_MAPS_API_KEY" || (echo "GOOGLE_MAPS_API_KEY is missing" && exit 1)
          test -n "$GOOGLE_MAP_ID" || (echo "GOOGLE_MAP_ID is missing" && exit 1)
          echo "All required secrets are configured."
      - name: Test with npx/tsx
        run: |
          npx tsx --test
  create-pull-request:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ success() }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Create Pull request
        run: gh pr create -B development -H ${{ github.ref_name }} --title "Merge ${{ github.ref_name }} into development" --body "Automatic PR from Github Actions"
