on:
  push:
    branches:
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
      GOOGLE_MAP_ID: ${{ secrets.GOOGLE_MAP_ID }}
    steps:
      - uses: actions/checkout@v6
      - name: Set up Node.js v25.9.0
        uses: actions/setup-node@v6
        with:
          node-version: "25"
      - name: Install dependencies
        run: |
          npm install
      - name: Test with npx/tsx
        run: |
          npx tsx --test
  create-pull-request:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ success() }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Create Pull request
        run: gh pr create -B development -H ${{ github.ref_name }} --title "Merge ${{ github.ref_name }} into development" --body "Automatic PR from Github Actions"
